/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.thymeleaf)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.session.spring.session.core)
    api(libs.org.thymeleaf.extras.thymeleaf.extras.springsecurity6)
    api(libs.org.projectlombok.lombok)
    api(libs.com.auth0.java.jwt)
    api(libs.jakarta.mail.jakarta.mail.api)
    runtimeOnly(libs.org.postgresql.postgresql)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.security.spring.security.test)
    annotationProcessor(libs.org.projectlombok.lombok)
}

group = "fhv.team11"
version = "0.0.1-SNAPSHOT"
description = "project.ems"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
